# Generated by Django 4.0.4 on 2022-06-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0002_alter_student_diplom'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='diplom',
        ),
        migrations.AddField(
            model_name='student',
            name='url_img',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
