# Generated by Django 4.0.4 on 2022-06-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0003_uploadmodel_remove_student_diplom_student_url_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='img_name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
