# Generated by Django 4.0.4 on 2022-06-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0004_student_img_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='url_stl',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
